sonar.projectKey=ddc_finances
sonar.organization=ddc1

sonar.sources=backend/core,backend/finances,frontend/src
sonar.tests=backend/tests,frontend/src/test

sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage-reports/coverage-python.xml

sonar.javascript.lcov.reportPaths=coverage-reports/lcov.info

sonar.exclusions=\
  .github/**,\
  utilities/**,\
  backend/core/migrations/**,\
  backend/core/management/**,\
  frontend/src/test/**,\
  backend/tests/**,\
  frontend/dist/**,\
  **/node_modules/**

sonar.security.hotspots.exclusions=\
  .github/**/*,\
  backend/tests/**/*,\
  backend/finances/settings.py,\
  frontend/src/test/**/*,\
  **/Dockerfile

sonar.security.exclusions=\
  .github/**/*,\
  backend/tests/**/*,\
  backend/finances/settings.py,\
  frontend/src/test/**/*

sonar.coverage.exclusions=\
  .github/**/*,\
  backend/tests/**/*,\
  backend/core/migrations/**/*,\
  frontend/src/test/**/*

sonar.cpd.exclusions=\
  .github/**/*,\
  **/i18n/**/*,\
  **/pages/**/*
