sonar.projectKey=ddc_finances
sonar.organization=ddc

sonar.sources=backend,frontend/src
sonar.tests=backend/tests,frontend/src/test

sonar.python.version=3.14
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.xunit.reportPath=backend/junit.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=\
  backend/tests/**/*,\
  backend/core/migrations/**/*,\
  backend/core/management/**/*,\
  frontend/src/test/**/*,\
  frontend/dist/**/*,\
  **/node_modules/**/*

sonar.coverage.exclusions=\
  backend/tests/**/*,\
  backend/core/migrations/**/*,\
  frontend/src/test/**/*
