sonar.projectKey=ddc_finances
sonar.organization=ddc-1

sonar.sources=backend,frontend/src
sonar.tests=backend/tests,frontend/src/test

sonar.python.version=3.14
sonar.python.coverage.reportPaths=backend/coverage-reports/coverage-python.xml

sonar.javascript.lcov.reportPaths=frontend/coverage-reports/lcov.info

sonar.exclusions=\
  .github/**/*,\
  backend/tests/**/*,\
  backend/core/migrations/**/*,\
  backend/core/management/**/*,\
  frontend/src/test/**/*,\
  frontend/dist/**/*,\
  **/node_modules/**/*

sonar.security.hotspots.exclusions=\
  .github/**/*,\
  backend/tests/**/*,\
  backend/finances/settings.py,\
  frontend/src/test/**/*,\
  **/Dockerfile

sonar.security.exclusions=\
  .github/**/*,\
  backend/tests/**/*,\
  backend/finances/settings.py,\
  frontend/src/test/**/*

sonar.coverage.exclusions=\
  .github/**/*,\
  backend/tests/**/*,\
  backend/core/migrations/**/*,\
  frontend/src/test/**/*

sonar.cpd.exclusions=\
  .github/**/*,\
  **/i18n/**/*,\
  **/pages/**/*
